/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderSuccesscopyRouteImport } from './routes/orderSuccess copy'
import { Route as OrderSuccessRouteImport } from './routes/orderSuccess'
import { Route as NotFoundRouteImport } from './routes/notFound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminAdminUsersRouteImport } from './routes/admin/_admin.users'
import { Route as AdminAdminProductsRouteImport } from './routes/admin/_admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/admin/_admin.orders'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/_admin.dashboard'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccesscopyRoute = OrderSuccesscopyRouteImport.update({
  id: '/orderSuccess copy',
  path: '/orderSuccess copy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/orderSuccess',
  path: '/orderSuccess',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/notFound',
  path: '/notFound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/orderSuccess': typeof OrderSuccessRoute
  '/orderSuccess copy': typeof OrderSuccesscopyRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/users': typeof AdminAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/orderSuccess': typeof OrderSuccessRoute
  '/orderSuccess copy': typeof OrderSuccesscopyRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/products/$id': typeof ProductsIdRoute
  '/products': typeof ProductsIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/users': typeof AdminAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/orderSuccess': typeof OrderSuccessRoute
  '/orderSuccess copy': typeof OrderSuccesscopyRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/_admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/_admin/orders': typeof AdminAdminOrdersRoute
  '/admin/_admin/products': typeof AdminAdminProductsRoute
  '/admin/_admin/users': typeof AdminAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/notFound'
    | '/orderSuccess'
    | '/orderSuccess copy'
    | '/orders'
    | '/profile'
    | '/register'
    | '/wishlist'
    | '/admin'
    | '/admin/login'
    | '/products/$id'
    | '/admin/'
    | '/products/'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/notFound'
    | '/orderSuccess'
    | '/orderSuccess copy'
    | '/orders'
    | '/profile'
    | '/register'
    | '/wishlist'
    | '/admin'
    | '/admin/login'
    | '/products/$id'
    | '/products'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/login'
    | '/notFound'
    | '/orderSuccess'
    | '/orderSuccess copy'
    | '/orders'
    | '/profile'
    | '/register'
    | '/wishlist'
    | '/admin/_admin'
    | '/admin/login'
    | '/products/$id'
    | '/admin/'
    | '/products/'
    | '/admin/_admin/dashboard'
    | '/admin/_admin/orders'
    | '/admin/_admin/products'
    | '/admin/_admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrderSuccesscopyRoute: typeof OrderSuccesscopyRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  WishlistRoute: typeof WishlistRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ProductsIdRoute: typeof ProductsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderSuccess copy': {
      id: '/orderSuccess copy'
      path: '/orderSuccess copy'
      fullPath: '/orderSuccess copy'
      preLoaderRoute: typeof OrderSuccesscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderSuccess': {
      id: '/orderSuccess'
      path: '/orderSuccess'
      fullPath: '/orderSuccess'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notFound': {
      id: '/notFound'
      path: '/notFound'
      fullPath: '/notFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/users': {
      id: '/admin/_admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/products': {
      id: '/admin/_admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/orders': {
      id: '/admin/_admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/dashboard': {
      id: '/admin/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrderSuccesscopyRoute: OrderSuccesscopyRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  WishlistRoute: WishlistRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ProductsIdRoute: ProductsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
